### ISSUE TITLE
AnyIO anyone?

### ISSUE THREAD

**Issue by parity3** [Tinche/quattro#1]
I feel like there needs to be at least *some* mention of the already-existing library that does this somewhere in the readme. I know quattro is probably much simpler, smaller-scoped etc etc but it would be really nice to know the "story" behind doing this project and in what situations this would be preferred over anyio.

**Comment by Tinche** [comment]
You kinda hit the nail on the had - the scope of this project is much smaller, and you should use it if you want something simple without buying into the huge anyio ecosystem. It's also likely something very close to this TaskGroup implementation will end up in Python's standard library (not from here though, the implementation here was borrowed from Yury Selivanov, and he's one of the asyncio maintainers).

I don't really feel like writing comparisons to other libs in the README - would you trust it if you found it there? It's the users job to consider these subtleties, and I think you did a good job yourself.

That said, maybe we could add a line or something. Dunno.

**Comment by parity3** [comment]
It's a fair point that an independent source has a better chance at being less biased / more trusted. It can be a win for many large asyncio projects to use this library to help adopt a standard policy or homogeneity in their code for task management, when they don't have the luxury of adding more complex dependencies.

If you were to decide to add something to the README you could put it here, after:

> In quattro, cancellation scopes cannot be shielded.

NEW:

> If you need shielding or level trigger semantics, you might consider using AnyIO, which has a broader goal of an API with identical behavior across multiple concurrency implementations.

It may also be nice to know in what cases a quick userland workaround would suffice, as in with the toy example in the README for send_goodbye_msg(), you could assign the move_on_after scope to a local variable so that in the finally clause you could determine if it was cancelled and do the right thing, or similar could be achieved by assigning a "success = True" local variable inside the try block.

**Comment by Tinche** [comment]
Good points.

I have also written an introduction and a small comparison with anyio over at https://discuss.python.org/t/introducing-quattro-simple-structured-concurrency-for-asyncio/13160, which kinda reiterates what we were discussing here.
